# Macro file for the initialization of example B3
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# create empty scene
#
/vis/scene/create
# open graphics (opengl QT)
/vis/open OGL
/vis/scene/add/axes 0 0 -1.9 0.6 m
/material/verbose 1

